name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests unittest2

      - name: Run Unit Tests
        run: |
          python -m unittest discover -s tests -p "test_registration.py"

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          ftp-server: ftp://ftp.ricode.it
          ftp-username: ${{ secrets.FTP_SMARTSHELF_USERNAME }}
          ftp-password: ${{ secrets.FTP_SMARTSHELF_PASSWORD }}
          local-dir: ./
          server-dir: /ricode.it/smartshelf
          excludes: |
            .git*
            .github*
          git-ftp-args: --insecure
